version: '3.3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: rt_chat_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  wb:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:123@db:5432/rt_chat_database
      - REDIS_URL=redis://redis:6379/0
      - CHANNEL_LAYERS_REDIS_URL=redis://redis:6379/1
      - SECRET_KEY=iamthedanger
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wb

volumes:
  postgres_data:
